# Generated by Django 4.2.1 on 2024-02-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geo_cordinates',
            name='name',
            field=models.CharField(default='manav', max_length=255),
            preserve_default=False,
        ),
    ]
