# Generated by Django 4.2.1 on 2024-02-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_geo_cordinates_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='allowed_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.TextField()),
            ],
        ),
    ]
